### PR TITLE
properly send lengths in Instruments.send_event

### PR DESCRIPTION
**Pull request by jhgg**

### CODE REVIEW

**Comment by jhgg** [comment]
@scohen

**Comment by scohen** [comment]
Add a test?

**Comment by jhgg** [comment]
I'm not sure the best way. The parser in fake statsd does not check the lengths. I could make it do that though... or I could just make another test that sends the raw packet data back and exact matches against it. Wdyt?

**Comment by scohen** [comment]
I have a slight preference for enhancing the fake statsd, since that could be useful for other tests.

**Comment by jhgg** [comment]
OK. Can we merge this now and I'll open a separate PR to fix the fake statsd parser afterwards, as this PR isn't really opened from a branch and I can't push to it.

I can't merge this either as no write access :(

**Pull request merged**
